### ISSUE TITLE
Custom Claims access from Firebase Auth Admin SDK

### ISSUE THREAD

**Issue by diego-paired** [RevenueCat/firestore-revenuecat-purchases#32]
Hello,

We have the extension up and running, generating subscriber and event data into Firestore.

We have not been able to access the custom claims described in the documentation, although with a slightly different use case. In our case we'd like to access it from our backend using the Node Firebase Auth library. 

Users authenticate their requests using a token provided by Firebase, that is then decoded on the backend side for every request. At this stage we'd like to also determine the users' entitlements and potentially reject a request not intended for non paying users.

The examples in the documentation use the client side SDK, is this possible to do from the Admin SDK?

Thanks in advance.

**Comment by alfondotnet** [comment]
Hey @diego-paired ,

sorry this request fell through the cracks, I'll try to route this to the appropriate person and get back to you

**Comment by Andre-lbc** [comment]
Hi,

I had a similar problem (in my case, setting a validation rule condition to only allow Firestore requests that have a "premium" entitlement), but after enabling custom claims in the plugin's configuration I've found a discrepancy between documentation and real data:

The documentation states that custom claims will contain a parameter named "activeEntitlements" ([here](https://www.revenuecat.com/docs/firebase-integration#checking-entitlement-access)), but that parameter is actually called "revenueCatEntitlements" ([here](https://github.com/RevenueCat/firestore-revenuecat-purchases/blob/28870aeaa5167d5d6ea18dd7cebae2e4de59e42e/functions/src/index.ts#L105)). I assumed this was a documentation typo and have been using "revenueCatEntitlements" ever since. 


@diego-paired, if you have your user's uid, I believe you can do something like this on server side:

``` Javascript
const { getAuth }  = require('firebase-admin/auth');

const user = await getAuth().getUser('[YOUR_FIREBASE_USER_UID]');
const activeEntitlements = user?.customClaims?.revenueCatEntitlements;
```

**Comment by diego-paired** [comment]
> Hi,
> 
> I had a similar problem (in my case, setting a validation rule condition to only allow Firestore requests that have a "premium" entitlement), but after enabling custom claims in the plugin's configuration I've found a discrepancy between documentation and real data:
> 
> The documentation states that custom claims will contain a parameter named "activeEntitlements" ([here](https://www.revenuecat.com/docs/firebase-integration#checking-entitlement-access)), but that parameter is actually called "revenueCatEntitlements" ([here](https://github.com/RevenueCat/firestore-revenuecat-purchases/blob/28870aeaa5167d5d6ea18dd7cebae2e4de59e42e/functions/src/index.ts#L105)). I assumed this was a documentation typo and have been using "revenueCatEntitlements" ever since.
> 
> @diego-paired, if you have your user's uid, I believe you can do something like this on server side:
> 
> ```js
> const { getAuth }  = require('firebase-admin/auth');
> 
> const user = await getAuth().getUser('[YOUR_FIREBASE_USER_UID]');
> const activeEntitlements = user?.customClaims?.revenueCatEntitlements;
> ```

Thank you Andre, I'll give it a go.
