### ISSUE TITLE
app_user_id is not always custom firebase uid - syncing via $RCAnon... uid instead

### ISSUE THREAD

**Issue by benedelstein** [RevenueCat/firestore-revenuecat-purchases#45]
Hi, I've setup the extension and am signing in users with ```Purchases.shared.login(uid)```. However, I've noticed that some webhook events send `app_user_id` still with the anonymous $RCAnon... value (even though my custom uid is linked as an alias). This seems to happen indeterminately, I've noticed it most often in TRANSFER events [1].

So when the extension tries to sync to firestore/auth claims via that uid, it sets phantom data and my actual uids' data is not updated.

Shouldn't the extension search the `aliases` array, and look for an element that is not an anon id, instead of just grabbing the `app_user_id`?

I posted a question in the forum [here](https://community.revenuecat.com/general-questions-7/for-users-with-custom-id-how-is-the-main-app-user-id-determined-2245?postid=7129#post7129), but I think this may be a bug with the extension, especially since the [setup guide says](https://www.revenuecat.com/docs/firebase-integration#2-set-firebase-user-identity-in-revenuecat) that linking user identity is required for the firestore integration. I assumed that meant that all extension events would be guaranteed to sync via the firebase uid.

--
[1] I read [here](https://www.revenuecat.com/docs/firebase-integration#2-set-firebase-user-identity-in-revenuecat) that the app_user_id is sent as the most recently seen alias, but that still doesn't match up with the behavior I'm seeing. If I sign out of one account, then sign into another, then restore purchases, the last seen ids for each of those accounts should still be the custom uids.

**Comment by yousefcat** [comment]
This issue was resolved within a support ticket. Just to summarize:

The Firebase RevenueCat extension currently reports the most recent App User ID within events. This was not ideal for since the goal was to sync the known App User IDs if they were available instead of anonymous IDs. Ben found a workaround within Firebase, and we have reported this as a feature request / product feedback to the team working in the area.

**Comment by ninjz** [comment]
@yousefcat @benedelstein What is the workaround that you came up with?

**Comment by raulmabe-labhouse** [comment]
@yousefcat so this issue is still not resolved yet? What's the workaround?

**Comment by Foixa** [comment]
any update? 

<img width="283" alt="Screenshot 2024-12-23 at 00 59 29" src="https://github.com/user-attachments/assets/244c01b5-b1c5-4716-87b6-ec2c68454b6d" />

**Comment by benedelstein** [comment]
> @yousefcat @benedelstein What is the workaround that you came up with?

I think my solution was to listen to doc creation events and check if the id was anonymous, and repost the data with the firebase id

**Comment by moertel** [comment]
> I think my solution was to listen to doc creation events and check if the id was anonymous, and repost the data with the firebase id

@yousefcat Shouldn't that be something that is handled by the extension itself? Either the extension makes a bold decision to always sync the `originalAppUserId` (so at least it's consistent), or it syncs all known IDs and aliases. The current 'pick and choose' approach causes stale data, function failures, and orphaned data sets in Firestore.

I'm on the verge of deleting the extension and building my own sync process from scratch. Really not seeing the benefit of this (other than the doc events that I can setup anyway by using the webhook?), especially seeing this unresolved on a conceptual level with only workarounds since over 2 years.
